-- 'TOTAL_DISTANCE'는 CONCAT를 통해 문자열로 변환되었기에 ORDER BY에 제대로 적용될 수 없음
-- 집계함수를 통해 재설정해주어야 함

SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1),"km") AS "TOTAL_DISTANCE", CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), "km") AS "AVERAGE_DISTANCE"
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;