SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
FROM FISH_INFO JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
GROUP BY FISH_INFO.FISH_TYPE, FISH_NAME
ORDER BY FISH_COUNT DESC;


-- ONLY FULL GROUP BY 발생
--  원인 : FISH_TYPE으로 그룹화한 후 FISH_NAME을 가져올 때, 어떤 값을 가져와야 하는지 모르는 것이 문제
--  해결 : GROUP BY에 FISH_NAME을 추가함